name: test

on:
  push:
    tags:
      - '!v*'
    branches:
      - '*'
  pull_request:

jobs:
  unittests:
    runs-on: ubuntu-latest
    container: projecteru2/yavirt:prebuild

    steps:
      - uses: actions/checkout@v2
      - name: unit tests
        run: make test
